/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Estudiantes;

/**
 *
 * @author pcdev
 */
public class frmEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form frmEstudiante
     */
    public frmEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 100, 20);

        txtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtId);
        txtId.setBounds(200, 80, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Celular");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 180, 90, 30);

        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtCelular);
        txtCelular.setBounds(200, 180, 190, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(40, 350, 80, 40);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(130, 350, 90, 40);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(230, 350, 90, 40);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(330, 350, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 130, 90, 30);

        txtNombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtNombre1);
        txtNombre1.setBounds(200, 130, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Curso");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 280, 90, 30);

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEdad);
        txtEdad.setBounds(200, 230, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Edad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 230, 90, 30);

        getContentPane().add(cmbCurso);
        cmbCurso.setBounds(200, 280, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ESTUDIANTES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 14, 380, 40);

        setBounds(0, 0, 475, 471);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
//        Estudiante estudiante = new Estudiante();
//        Connection con = Conexion.conectar();
//        String sql = "SELECT * FROM estudiantes WHERE documento = ?";
//        ResultSet rs;
//        try {
//            //Prepara los sentencia SQL a ejecutar
//            PreparedStatement sp = con.prepareStatement(sql);
//            sp.setInt(1, Integer.parseInt(txtId.getText()));
//            //Ejecuata la sentencia y retorna los datos
//            rs = sp.executeQuery();
//            if (rs.next()) {
//                estudiante.setNombre(rs.getString("nombre"));
//                estudiante.setEstado(rs.getBoolean("estado"));
//                estudiante.setCiclo(rs.getString("ciclo"));
//                estudiante.setSexo(rs.getString("genero"));
//
//                txtCelular.setText(estudiante.getNombre());
//                if (estudiante.getSexo().equals("Femenino")) {
//                    rbFemenino.setSelected(true);
//                } else {
//                    rbMasculino.setSelected(true);
//                }
//
//                cmbCiclo.setSelectedItem(estudiante.getCiclo());
//                chkEstado.setSelected(estudiante.isEstado());
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(frmEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(frmEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
//        Estudiante estu = new Estudiante();
//        //Guardo los datos de la vista en el objeto Estudiante
//        estu.setDocumento(Integer.parseInt(txtId.getText()));
//        estu.setNombre(txtCelular.getText());
//        estu.setSexo(rbFemenino.isSelected() ? "Femenino" : "Masculino");
//        estu.setCiclo(cmbCiclo.getSelectedItem().toString());
//        estu.setEstado(chkEstado.isSelected());
//
//        //Conecto a BD
//        Connection con = Conexion.conectar();
//        String sql = "UPDATE Estudiantes SET nombre = ?, genero = ?, ciclo=?, estado=? "
//        + " WHERE documento = ?";
//        try {
//            //Preparo la sentencia de SQL
//            PreparedStatement psm = con.prepareStatement(sql);
//            //Reemplazo los parámetros del query (?) por los valores
//            psm.setString(1, estu.getNombre());
//            psm.setString(2, estu.getSexo());
//            psm.setString(3, estu.getCiclo());
//            psm.setBoolean(4, estu.isEstado());
//            psm.setInt(5, estu.getDocumento());
//            //Ejecuto el query
//            psm.executeUpdate();
//            //Se muestra el mensaje
//            JOptionPane.showMessageDialog(this, "Editado con éxito");
//        } catch (SQLException ex) {
//            Logger.getLogger(EstudianteDAO.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        //Cerrar conexión
//        try {
//            con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(EstudianteDAO.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
//        Estudiante estu = new Estudiante();
//        //Guardo los datos de la vista en el objeto Estudiante
//        estu.setDocumento(Integer.parseInt(txtId.getText()));
//
//        //Conecto a BD
//        Connection con = Conexion.conectar();
//        String sql = "DELETE FROM Estudiantes WHERE documento = ?";
//        try {
//            PreparedStatement psm = con.prepareStatement(sql);
//            psm.setInt(1, estu.getDocumento());
//            psm.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Registro Eliminado");
//        } catch (SQLException ex) {
//            Logger.getLogger(EstudianteDAO.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        //Cerrar conexión
//        try {
//            con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(EstudianteDAO.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
