/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import modelo.Curso;
import modelo.Estudiantes;
import modelo.Profesor;

/**
 *
 * @author pcdev
 */
public class frmReportes extends javax.swing.JFrame {

    DefaultTableModel moTabla = new DefaultTableModel();
    DefaultTableModel moTablaCurso = new DefaultTableModel();
    DefaultListModel moListaCurso = new DefaultListModel();

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
        iniciarModelo();
    }

    public void iniciarModelo() {
        Profesor profe = new Profesor();
        String[] cabecera = {"ID", "Nombre", "Correo", "Edad"};
        moTabla.setColumnIdentifiers(cabecera);
        for (Profesor p : profe.listar()) {
            moTabla.addRow(new Object[]{p.getId(), p.getNombre(), p.getCorreo(), p.getEdad()});
        }
        tblProfesores.setModel(moTabla);

        Curso curso = new Curso();
        for (Curso c : curso.listar()) {
            moListaCurso.addElement(c.getId() + "-" + c.getNombre());
        }
        lstCursos.setModel(moListaCurso);

        String[] cabeceraCurso = {"ID", "Nombre", "Celular","Edad"};
        moTablaCurso.setColumnIdentifiers(cabeceraCurso);
//        for (Curso c : curso.listar()) {
//            moTablaCurso.addRow(new Object[]{c.getId(), c.getNombre(), c.getCapacidad()});
//        }
        tblEstudiantesCurso.setModel(moTablaCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfesores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEstudiantesCurso = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tblProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProfesores);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 331, 120);

        jTabbedPane1.addTab("Profesores", jPanel1);

        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(40, 73, 363, 263);

        jTabbedPane1.addTab("Estudiantes", jPanel2);

        jPanel3.setLayout(null);

        lstCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursos);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(30, 80, 130, 190);

        tblEstudiantesCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblEstudiantesCurso);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(190, 80, 280, 190);

        jTabbedPane1.addTab("Cursos", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 30, 420, 340);

        setBounds(0, 0, 535, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void lstCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosMouseClicked
        Curso curso = new Curso();
        int id = Integer.parseInt(lstCursos.getSelectedValue().split("-")[0]);
        moTablaCurso.setRowCount(0);
        for (Estudiantes alumno : curso.listarEstudiantes(id)) {
            moTablaCurso.addRow(new Object[]{alumno.getId(), alumno.getNombre(), alumno.getCelular(), alumno.getEdad()});
        }
    }//GEN-LAST:event_lstCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JTable tblEstudiantesCurso;
    private javax.swing.JTable tblProfesores;
    // End of variables declaration//GEN-END:variables
}
